In [1]:
'''1. Implement the function S = IsSquare(A) that checks the dimension of input matrix A, 
and returns 1 if the input matrix is square and 0 otherwise'''
import numpy as np 
def IsSquare(A):
    arr = np.array(A) # if user input list convert it into numpy array 
    #comapare row of shape with shape of coloumns count from last index incase user enter matrix more  than 2 dim
    if arr.shape[-2] ==arr.shape[-1]: 
        return 1
    else :
        return 0

nn =np.array([[1,2],[3,4]])
print(nn.shape[-2])
IsSquare(nn)
print(nn[0,0])

2
1


In [2]:
'''2. Implement the function N = Props(A) that checks the properties of the input matrix A:
2.1 checks the input matrix is square,
2.2 computes the matrix rank, prints the rank value (hint: use numpy method)
2.3 computes the matrix determinant (hint: use numpy method) and prints its value
2.4 returns 1 if the input matrix has rank = no. of rows in matrix A and 0 otherwise
'''
def Props(A) :
    A = np.array(A) # if user input list convert it into numpy array 
    rank = 0
    if IsSquare(A) :
        rank = np.linalg.matrix_rank(A)
        print(f'rank = {rank}')
        print(f'matrix detrminant = {np.linalg.det(A)}')
        if A.shape[-2]  == rank :
            return 1
        else :
            print("matrix rank not equal no. row")
            return 0 
    else :
        print('matrix not square')
        return 0
    
Props(nn)

rank = 2
matrix detrminant = -2.0000000000000004


1

In [3]:
'''
3. Compose the equations corresponding to the two word-problems below 
and put them in matrix-vector form AX = B. Call "Props" to find more about their properties.
'''

#System 1:
#['sunflowers','roses' ,'daisies' ]
A=np.array([[1,1,1],[1.50,5.75,2.60],[0,-1,1]],dtype=np.float64)
B=np.array([200,589.5,20],dtype=np.float64).reshape(-1,1)
Props(A)
#System 2:
#['potatoes','chicken','oil','price']
print('------------------------------')
A2=np.array([[2,1,3],[4,2,6],[1,1,-1]],dtype=np.float64)
B2=np.array([0,0,0],dtype=np.float64).reshape(-1,1)
Props(A2)

rank = 3
matrix detrminant = 5.35
------------------------------
rank = 2
matrix detrminant = 0.0
matrix rank not equal no. row


0

In [4]:
'''
4. Implement the function reducerow(C,pivotrow(row index),targetrow(row index),pivot(index))
4.1 Takes an input matrix C, index of a pivot row vector, index of a target row vector, index of a pivot element. It returns nothing but overrides the matrix C
4.2 Checks if the pivot element = 1 otherwise perform vector operation to make it = 1
4.3 Uses vector operations using the two vectors “pivotrow” & “targetrow” to make the element corresponding to the pivot element in the targetrow vector = 0
'''
def reducerow(C,pivotrow,targetrow,pivot) :
    pivot_element =C[pivotrow,pivot]
    if pivot_element != 1 :
        C[pivotrow,pivot : ] /=pivot_element  #make pivot equal to 1
    C[targetrow,:] -= C[targetrow,pivot]*C[pivotrow,:]
    return C
        

In [5]:
'''5. Implement the function f = SolveLinearSystem (A,B)
5.1 Takes as an input coefficient matrix A and target vector B
5.2 Adjoins A and B then perform row reduction operations using “reducerow” trying to convert it A’s columns into an identity matrix
5.3 returns f = the summation of A’s columns elements after row reduction'''

def solveLinearSystem(A,B):
    join_m=np.hstack((A,B))  #make augmented matrix
    for i in range(join_m.shape[0]):
        for j in range(join_m.shape[0]):
            if i!=j:
                join_m=reducerow(join_m,i,j,i)
   
    return join_m

In [11]:
'''6. Call “SolveLinearSystem” to solve the systems 1 and 2 you previously created in 3'''
print(solveLinearSystem(A,B))
print(solveLinearSystem(A2,B2))

[[ 1.  0.  0. 80.]
 [ 0.  1.  0. 50.]
 [ 0.  0.  1. 70.]]
[[nan nan nan nan]
 [nan nan nan nan]
 [ 0. nan nan nan]]


C:\Users\ahmed\AppData\Local\Temp/ipykernel_856/4280432617.py:10: RuntimeWarning: invalid value encountered in true_divide
  C[pivotrow,pivot : ] /=pivot_element  #make pivot equal to 1


In [7]:
'''7. Elaborate your solution (write commented text)
7.1 If f<3 explain the reason and propose one possible solution (if any) to the equation system
7.2 otherwise write down the system solution
'''
f =  np.sum(np.sum(solveLinearSystem(A,B) , axis = 0)[:3])
print(f) #if f <3 then there is vector dependent


3.0


In [8]:
'''8. Type these code lines and check your answers for systems 1 and 2
x = np.linalg.solve(A, B) # Solves a full-rank system of linear equations ax = b.
print(x)
np.allclose(np.dot(A, x), B) # Returns True if two arrays are element-wise equal within a tolerance.'''
print(np.linalg.solve(A, B))
print(np.allclose(np.dot(A,B) , B))
#print(np.linalg.solve(A2, B2)) #erroe because of system detrminent equal to zero


[[80.]
 [50.]
 [70.]]
False


In [12]:
'''9. Call the same function “SolveLinearSystem” to get inv(A) for systems 1 and 2'''
identity_array= np.array([[1,0,0],[0,1,0],[0,0,1]])
#AI = A    ,   A^-1 A I=  A^-1 A  ,  I = A^-1    ,    
print(solveLinearSystem(A,identity_array)) # build augmanted matrix  [A|I]
print(solveLinearSystem(A,identity_array)[:,3:])
print(solveLinearSystem(A2,identity_array)[:,3:]) #detrimnent = 0 so there is no inverse

[[ 1.          0.          0.          1.56074766 -0.37383178 -0.58878505]
 [ 0.          1.          0.         -0.28037383  0.18691589 -0.20560748]
 [ 0.          0.          1.         -0.28037383  0.18691589  0.79439252]]
[[ 1.56074766 -0.37383178 -0.58878505]
 [-0.28037383  0.18691589 -0.20560748]
 [-0.28037383  0.18691589  0.79439252]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


C:\Users\ahmed\AppData\Local\Temp/ipykernel_856/4280432617.py:10: RuntimeWarning: divide by zero encountered in true_divide
  C[pivotrow,pivot : ] /=pivot_element  #make pivot equal to 1
C:\Users\ahmed\AppData\Local\Temp/ipykernel_856/4280432617.py:10: RuntimeWarning: invalid value encountered in true_divide
  C[pivotrow,pivot : ] /=pivot_element  #make pivot equal to 1


In [13]:
'''10. Check your solution if possible using np.linalg.inv() function'''
print(np.linalg.inv(A))
print(solveLinearSystem(A2,identity_array)[:,3:]) #LinAlgError: Singular matrix 

[[ 1.56074766 -0.37383178 -0.58878505]
 [-0.28037383  0.18691589 -0.20560748]
 [-0.28037383  0.18691589  0.79439252]]


LinAlgError: Singular matrix