In [1]:
import numpy as np
from scipy.linalg import lu

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

In [2]:
A = np.array([[2,5],[1,2]])
y=np.array([[21],[8]])
h_wL =np.array([[1,0],[0.5,1]])
h_wU =np.array([[2,5],[0,-0.5]])
m = np.linalg.inv(h_wL)@y
x=np.linalg.inv(h_wU)@m
print(f'A = {A}')
print(f'LU = {h_wL@h_wU}')
print(f'm= {m}')
print(f'x= {x}')


A = [[2 5]
 [1 2]]
LU = [[2. 5.]
 [1. 2.]]
m= [[21. ]
 [-2.5]]
x= [[-2.]
 [ 5.]]


In [3]:
A = np.array([[2,5],[1,2]])
y=np.array([[21],[8]])
p,l,u = lu(A)
print(f'p = {p}')
print(f'L = {l}')
print(f'U = {u}')

p = [[1. 0.]
 [0. 1.]]
L = [[1.  0. ]
 [0.5 1. ]]
U = [[ 2.   5. ]
 [ 0.  -0.5]]


In [4]:
m = np.linalg.inv(l)@y
x=np.linalg.inv(u)@m
print(f'A = {A}')
print(f'LU = {l@u}')
print(f'm= {m}')
print(f'x= {x}')

A = [[2 5]
 [1 2]]
LU = [[2. 5.]
 [1. 2.]]
m= [[21. ]
 [-2.5]]
x= [[-2.]
 [ 5.]]


In [5]:
A = np.array([[1, 1, 1], [4, 3, -1], [3, 5, 3]])
y=np.array([[1], [6], [4]])
h_wL =np.array([[1, 0, 0], [4, 1, 0], [3, -2, 1]])
h_wU =np.array([[1, 1, 1], [0, -1, -5], [0, 0, -10]])
m = np.linalg.inv(h_wL)@y
x=np.linalg.inv(h_wU)@m
print(f'A = {A}')
print(f'LU = {h_wL@h_wU}')
print(f'm= {m}')
print(f'x= {x}')

A = [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
LU = [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
m= [[1.]
 [2.]
 [5.]]
x= [[ 1. ]
 [ 0.5]
 [-0.5]]


In [6]:
A = np.array([[1, 1, 1], [4, 3, -1], [3, 5, 3]])
y=np.array([[1], [6], [4]])
p,l,u = lu(A)
print(f'p = {p}')
print(f'L = {l}')
print(f'U = {u}')

p = [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L = [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
U = [[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]


In [7]:
y =np.linalg.inv(p)@y
m = np.linalg.inv(l)@y
x=np.linalg.inv(u)@m
print(f'A = {A}')
print(f'LU = {l@u}')
print(f'm= {m}')
print(f'x= {x}')

A = [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
LU = [[ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  1.  1.]]
m= [[ 6.        ]
 [-0.5       ]
 [-0.45454545]]
x= [[ 1. ]
 [ 0.5]
 [-0.5]]


### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

In [8]:
A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])



In [9]:
## Jacobi Not Vectorized
epsilon = 0.00001
x1=-0.2000
x2=0.2222
x3=-0.4286
sol = [[x1,x2,x3]]
print(0,x1,x2,x3)
for i in range (1,100):
    x1 = (2*sol[-1][1] - 3 * sol[-1][2] - 1)/5
    x2 = (3 * sol[-1][0] - sol[-1][2] +2)/9
    x3 =(-2 * sol[-1][0] + sol[-1][1] + 3)/-7
    print(i,x1,x2,x3)
    if np.abs(x1-sol[-1][0])< epsilon or np.abs(x2-sol[-1][1])< epsilon or np.abs(x3-sol[-1][2])< epsilon :
        break
    sol.append([x1,x2,x3])



0 -0.2 0.2222 -0.4286
1 0.14604 0.20317777777777776 -0.517457142857143
2 0.1917453968253969 0.3283974603174603 -0.4158711111111111
3 0.18088165079365076 0.3323452557319224 -0.42070095238095234
4 0.18535867372134035 0.3292606560846561 -0.4243688505920887
5 0.18632557278911568 0.3311605413062344 -0.4226490440917107
6 0.1860536429775202 0.33129175138433975 -0.4226441993897147


In [10]:
## Gauss-Seidel Not Vectorized
epsilon = 0.00001
x1=-0.2000
x2=0.1556
x3=-0.5079
sol = []
x1 = (2*x2 - 3 * x3 - 1)/5
x2 = (3 * x1 - x3 +2)/9
x3 =(-2 * x1 + x2 + 3)/-7
print(0,x1,x2,x3)
sol.append([x1,x2,x3])
for i in range (1,100):
    x1 = (2*x2 - 3 * x3 - 1)/5
    x2 = (3 * x1 - x3 +2)/9
    x3 =(-2 * x1 + x2 + 3)/-7
    print(i,x1,x2,x3)
    if (np.abs(np.array([x1,x2,x3])-np.array(sol[-1]))<epsilon).any():#np.abs(x1-sol[-1][0])< epsilon or np.abs(x2-sol[-1][1])< epsilon or np.abs(x3-sol[-1][2])< epsilon :
        break
    sol.append([x1,x2,x3])

0 0.16698 0.3343155555555556 -0.42862222222222224
1 0.19089955555555557 0.3334800987654321 -0.42166871252204585
2 0.18639326701940034 0.33120539039780517 -0.4226312651941435
3 0.18606091527560817 0.33120155678010754 -0.42272567517555587


In [11]:
A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])
y = np.array([[-1],[2],[3]])

diag = np.diag(np.diag(A))
l = -np.tril(A, -1) 
u = -np.triu(A, 1)
print(f'A = {A}')
print(f'diag = {diag}')
print(f'l = {l}')
print(f'u = {u}')
print(diag-l-u)

A = [[ 5 -2  3]
 [-3  9  1]
 [ 2 -1 -7]]
diag = [[ 5  0  0]
 [ 0  9  0]
 [ 0  0 -7]]
l = [[ 0  0  0]
 [ 3  0  0]
 [-2  1  0]]
u = [[ 0  2 -3]
 [ 0  0 -1]
 [ 0  0  0]]
[[ 5 -2  3]
 [-3  9  1]
 [ 2 -1 -7]]


In [12]:
#guess cycle


In [13]:
## Jacobi Vectorized
epsilon = 0.00001
Tgus = np.linalg.inv(diag) @ (l+u)
Cgus = np.linalg.inv(diag) @ y
# x = np.zeros((3,1))

x = np.array([[-0.2000],[0.2222],[-0.4286]])
x_brev=[x]
for i in range (10):
    x = Tgus @ x +Cgus
    print(i+1,x.reshape(-1))
    if (np.abs(np.array(x)-np.array(x_brev[-1]))<epsilon).any():
        break
    x_brev.append(x)

1 [ 0.14604     0.20317778 -0.51745714]
2 [ 0.1917454   0.32839746 -0.41587111]
3 [ 0.18088165  0.33234526 -0.42070095]
4 [ 0.18535867  0.32926066 -0.42436885]
5 [ 0.18632557  0.33116054 -0.42264904]
6 [ 0.18605364  0.33129175 -0.4226442 ]


In [14]:
## Gauss-Seidel Vectorized
epsilon = 0.00001
Tgus = np.linalg.inv(diag-l) @ u
Cgus = np.linalg.inv(diag-l) @ y
# x = np.zeros((3,1))

x = np.array([[-0.2000],[0.2222],[-0.4286]])
x_brev=[x]
for i in range (10):
    x = Tgus @ x +Cgus
    print(i+1,x.reshape(-1))
    if (np.abs(np.array(x)-np.array(x_brev[-1]))<epsilon).any():
        break
    x_brev.append(x)

1 [ 0.14604     0.31852444 -0.43234921]
2 [ 0.1868193   0.33253412 -0.42269936]
3 [ 0.18663327  0.33139991 -0.42259048]
4 [ 0.18611425  0.3312148  -0.42271233]
5 [ 0.18611332  0.33122803 -0.42271448]


### Use np.linalg.solve() to solve the previous system and compare the results.

In [15]:
P,L,U = lu(A)
np.linalg.solve(A,y)

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

In [16]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [-0.6       ,  1.        ,  0.        ],
       [ 0.4       , -0.02564103,  1.        ]])

In [18]:
U

array([[ 5.        , -2.        ,  3.        ],
       [ 0.        ,  7.8       ,  2.8       ],
       [ 0.        ,  0.        , -8.12820513]])